services:
   postgres:
      image: postgres:latest
      container_name: database
      restart: always
      env_file: .env
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
         PGDATA: ${POSTGRES_DATA}
      ports:
         - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      expose:
         - "${POSTGRES_PORT}"
      volumes:
         - postgres-data:${POSTGRES_DATA}

volumes:
   postgres-data:
